// This file is generated by Gemini.

'use server';

/**
 * @fileOverview An AI agent that suggests optimal appointment times for patients, 
 * considering driver availability, predicted traffic, and appointment priorities.
 *
 * - suggestAppointmentTimes - A function that suggests appointment times.
 * - SuggestAppointmentTimesInput - The input type for the suggestAppointmentTimes function.
 * - SuggestAppointmentTimesOutput - The return type for the suggestAppointmentTimes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestAppointmentTimesInputSchema = z.object({
  pickupLocation: z.string().describe('The pickup location of the patient.'),
  dropoffLocation: z.string().describe('The dropoff location (clinic/hospital).'),
  earliestTime: z.string().describe('The earliest acceptable appointment time (ISO format).'),
  latestTime: z.string().describe('The latest acceptable appointment time (ISO format).'),
  priority: z.enum(['high', 'medium', 'low']).default('medium').describe('The priority of the appointment.'),
});

export type SuggestAppointmentTimesInput = z.infer<typeof SuggestAppointmentTimesInputSchema>;

const SuggestAppointmentTimesOutputSchema = z.object({
  suggestedTimes: z.array(
    z.string().describe('A suggested appointment time (ISO format).')
  ).describe('A list of suggested appointment times based on driver availability, traffic, and priority.'),
  reasoning: z.string().describe('The reasoning behind the suggested times.'),
});

export type SuggestAppointmentTimesOutput = z.infer<typeof SuggestAppointmentTimesOutputSchema>;

export async function suggestAppointmentTimes(input: SuggestAppointmentTimesInput): Promise<SuggestAppointmentTimesOutput> {
  return suggestAppointmentTimesFlow(input);
}

const suggestAppointmentTimesPrompt = ai.definePrompt({
  name: 'suggestAppointmentTimesPrompt',
  input: {schema: SuggestAppointmentTimesInputSchema},
  output: {schema: SuggestAppointmentTimesOutputSchema},
  prompt: `You are an AI assistant that suggests optimal appointment times for patients seeking medical rides.

  Consider the following factors when suggesting times:
  - Driver availability: Prioritize times when drivers are likely to be available in the specified area.
  - Predicted traffic: Avoid times with heavy traffic to ensure timely arrival.
  - Appointment priority: High-priority appointments should be scheduled sooner.

  Given the following information, suggest 3 optimal appointment times within the acceptable time window. Return times in ISO format.

  Pickup Location: {{{pickupLocation}}}
  Dropoff Location: {{{dropoffLocation}}}
  Earliest Time: {{{earliestTime}}}
  Latest Time: {{{latestTime}}}
  Priority: {{{priority}}}
  
  Format your response as a JSON object with "suggestedTimes" (an array of ISO formatted times) and a "reasoning" field.
  `,
});

const suggestAppointmentTimesFlow = ai.defineFlow(
  {
    name: 'suggestAppointmentTimesFlow',
    inputSchema: SuggestAppointmentTimesInputSchema,
    outputSchema: SuggestAppointmentTimesOutputSchema,
  },
  async input => {
    const {output} = await suggestAppointmentTimesPrompt(input);
    return output!;
  }
);
